package com.moonbench.bifrost.rp5
import android.app.AlertDialog
import android.os.Bundle
import android.widget.*
import androidx.appcompat.app.AppCompatActivity

class ThumbstickViewAreaEditorActivity:AppCompatActivity(){
 private lateinit var editor:ThumbstickViewAreaEditorView;private lateinit var preview:ThumbstickLivePreview;private lateinit var store:FineTuneStore;private var name:String?=null;private var mode=ThumbstickColourMode.AVERAGE;private var captureMode=0
 override fun onCreate(b:Bundle?){super.onCreate(b);store=FineTuneStore(this);name=intent.getStringExtra(EXTRA_PROFILE_NAME);setContentView(build());store.find(name.orEmpty())?.let{mode=it.colourMode;editor.setRegions(it.leftViewArea,it.rightViewArea)};editor.onPreviewRequested={l,r->preview.preview(l,r,mode)};chooseCaptureSource()}
 private fun build()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(0xFF000000.toInt());
  addView(TextView(this@ThumbstickViewAreaEditorActivity).apply{text="VIEWING PROFILE — SAMPLE AREA";textSize=18f;setTextColor(-1);setPadding(12,10,12,4)})
  addView(TextView(this@ThumbstickViewAreaEditorActivity).apply{text="Define the reusable screen viewing areas used by Ambient. Move the BLUE left and ORANGE right areas. Each thumb-stick LED previews its own sampled colour.";textSize=11f;setTextColor(0xFFCCCCCC.toInt());setPadding(12,0,12,6)})
  val modeSpinner=Spinner(this@ThumbstickViewAreaEditorActivity);val modes=listOf(ThumbstickColourMode.FIFTY_FIFTY to "50/50",ThumbstickColourMode.AVERAGE to "Average Colour",ThumbstickColourMode.CLOSE_MATCH to "Close Match Colour",ThumbstickColourMode.MOST_DOMINANT to "Most Dominant Colour",ThumbstickColourMode.DOMINANT_PRIME to "Dominant Prime Colour");modeSpinner.adapter=ArrayAdapter(this@ThumbstickViewAreaEditorActivity,android.R.layout.simple_spinner_dropdown_item,modes.map{it.second});modeSpinner.setSelection(modes.indexOfFirst{it.first==mode}.coerceAtLeast(0));var spinnerReady=false;modeSpinner.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:android.view.View?,pos:Int,id:Long){mode=modes[pos].first;if(spinnerReady&&::editor.isInitialized)preview.preview(editor.leftRegion,editor.rightRegion,mode);spinnerReady=true};override fun onNothingSelected(p:AdapterView<*>?) {}};addView(modeSpinner,LinearLayout.LayoutParams(-1,-2))
  editor=ThumbstickViewAreaEditorView(this@ThumbstickViewAreaEditorActivity);addView(editor,LinearLayout.LayoutParams(-1,0,1f));addView(LinearLayout(this@ThumbstickViewAreaEditorActivity).apply{addView(Button(this@ThumbstickViewAreaEditorActivity).apply{text="SAVE";setOnClickListener{save()}});addView(Button(this@ThumbstickViewAreaEditorActivity).apply{text="RESET";setOnClickListener{editor.reset()}});addView(Button(this@ThumbstickViewAreaEditorActivity).apply{text="EXIT";setOnClickListener{finish()}})})
 }
 private fun chooseCaptureSource(){AlertDialog.Builder(this).setTitle("Select Capture Type").setMessage("Choose how this Viewing Profile should be created. Live Capture continuously updates the screen image. Still Capture freezes one captured frame for positioning the viewing areas.").setItems(arrayOf("LIVE CAPTURE","STILL CAPTURE")){_,which->captureMode=which;if(::preview.isInitialized)preview.stop();preview=ThumbstickLivePreview(this,{editor.setPreviewFrame(it)},{l,r->editor.setSampledColors(l,r)});if(which==0)preview.start() else preview.captureOnce();preview.preview(editor.leftRegion,editor.rightRegion,mode)}.setNegativeButton("CANCEL"){_,_->finish()}.show()}
 override fun onResume(){super.onResume();if(::preview.isInitialized&&captureMode==0)preview.start()}
 override fun onPause(){if(::preview.isInitialized)preview.stop();super.onPause()}
 private fun save(){val input=EditText(this).apply{hint="Viewing profile name";setText(name.orEmpty())};AlertDialog.Builder(this).setTitle("Save Viewing Profile").setMessage("This saves the Sample Area as a reusable Ambient Viewing Profile. Fine Tune can select it for Ambient screen matching.").setView(input).setNegativeButton("CANCEL",null).setPositiveButton("SAVE"){_,_->val n=input.text.toString().trim();if(n.isNotEmpty()){store.save(FineTuneProfile(n,editor.leftRegion,editor.rightRegion,mode));name=n;finish()}}.show()}
 companion object{const val EXTRA_PROFILE_NAME="fine_tune_profile_name"}
}